In [2]:
import pandas as pd
import numpy as np

## Importing the dataset

In [3]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
data.shape

(10000, 14)

# Data Preprocessing

### Checking for null values

In [5]:
data.isnull().any()
# No null values

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [6]:
x = data.iloc[:,3:-1]
y = data.iloc[:,-1]

## Encoding the categorical variable

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x['Gender'] = le.fit_transform(x['Gender'])

In [8]:
# Performing One Hot Encoding in the Geography column as there is no order relationship in this column
x = pd.get_dummies(x, drop_first = True)
x

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  
0                  1        101348.88                  0                0  
1                  1        112542.58                  0                1  
2                  0        113931.57                  0                0  
3                  0         93826.63                  0                0  
4                  1         79084.10                  0                1  
...              ...              ...                ...              ...  
9995               0         96270.64                  0                0  
9996               1        101699.77                  0                0  
9997               1         42085.58                  0                0  
9998               0         92888.52                  1                0  
9999               0         38190.78                  0                0  

[10000 rows x 11 columns]

## Feature Scaling
- In Deep Learning it is necessary to scale all the feature columns, be it either categorical or numerical

In [9]:
cols = x.columns
cols

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Geography_Germany',
       'Geography_Spain'],
      dtype='object')

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x = pd.DataFrame(x, columns = cols)
x

CreditScore    Gender       Age    Tenure   Balance  NumOfProducts  \
0       -0.326221 -1.095988  0.293517 -1.041760 -1.225848      -0.911583   
1       -0.440036 -1.095988  0.198164 -1.387538  0.117350      -0.911583   
2       -1.536794 -1.095988  0.293517  1.032908  1.333053       2.527057   
3        0.501521 -1.095988  0.007457 -1.387538 -1.225848       0.807737   
4        2.063884 -1.095988  0.388871 -1.041760  0.785728      -0.911583   
...           ...       ...       ...       ...       ...            ...   
9995     1.246488  0.912419  0.007457 -0.004426 -1.225848       0.807737   
9996    -1.391939  0.912419 -0.373958  1.724464 -0.306379      -0.911583   
9997     0.604988 -1.095988 -0.278604  0.687130 -1.225848      -0.911583   
9998     1.256835  0.912419  0.293517 -0.695982 -0.022608       0.807737   
9999     1.463771 -1.095988 -1.041433 -0.350204  0.859965      -0.911583   

      HasCrCard  IsActiveMember  EstimatedSalary  Geography_Germany  \
0      0.646092        0.970243         0.021886          -0.578736   
1     -1.547768        0.970243         0.216534          -0.578736   
2      0.646092       -1.030670         0.240687          -0.578736   
3     -1.547768       -1.030670        -0.108918          -0.578736   
4      0.646092        0.970243        -0.365276          -0.578736   
...         ...             ...              ...                ...   
9995   0.646092       -1.030670        -0.066419          -0.578736   
9996   0.646092        0.970243         0.027988          -0.578736   
9997  -1.547768        0.970243        -1.008643          -0.578736   
9998   0.646092       -1.030670        -0.125231           1.727904   
9999   0.646092       -1.030670        -1.076370          -0.578736   

      Geography_Spain  
0           -0.573809  
1            1.742740  
2           -0.573809  
3           -0.573809  
4            1.742740  
...               ...  
9995        -0.573809  
9996        -0.573809  
9997        -0.573809  
9998        -0.573809  
9999        -0.573809  

[10000 rows x 11 columns]

## Splitting into train and test set

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [12]:
x_train.shape

(8000, 11)

In [13]:
x_test.shape

(2000, 11)

In [29]:
from tensorflow import keras

In [31]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Embedding, Dropout,Flatten, LeakyReLU, BatchNormalization
from tensorflow.keras.activations import relu, sigmoid

In [32]:
def create_model(layers, activation):
    model = Sequential()
    for i, nodes in enumerate(layers):
        if i == 0:
            model.add(Dense(nodes, input_dim = x_train.shape[1])) 
            # Need to give number of independent features in the first hidden layer
            model.add(Activation(activation))
            model.add(Dropout(0.3))
        else:
            model.add(Dense(nodes))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
    
    # Defining the output layer seperately
    model.add(Dense(units = 1, kernel_initializer = 'glorot_uniform', activation = 'sigmoid'))
    # Compiling the model
    model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return(model)


model = KerasClassifier(build_fn = create_model, verbose = 0)
#build_fn contains user defined function for adding layers and activation functions for different combinations

layers = [[20],[40, 20],[45, 30, 15]]
# Here there is:
# 1 layer with 20 hidden neurons
# 2 layers with 40 and 20 hidden neurons
# 3 layers with 45, 30 , 15 hidden neurons
activations = ['sigmoid','relu']
param_grid = dict(layers = layers, activation = activations, batch_size = [128,256], epochs = [30])
grid = GridSearchCV(estimator = model, param_grid = param_grid, cv = 5)


In [33]:
param_grid

{'layers': [[20], [40, 20], [45, 30, 15]],
 'activation': ['sigmoid', 'relu'],
 'batch_size': [128, 256],
 'epochs': [30]}

In [34]:
from time import time
start = time()
grid.fit(x_train, y_train)
end = time()
print(end-start)

129.80865597724915


In [35]:
print(grid.best_score_)
print(grid.best_params_)

0.856000018119812
{'activation': 'relu', 'batch_size': 128, 'epochs': 30, 'layers': [45, 30, 15]}


In [36]:
y_pred = grid.predict(x_test)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [37]:
y_pred = y_pred > 0.6
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
score = accuracy_score(y_test, y_pred)

In [39]:
print(cm)
print(score)

[[1541   54]
 [ 220  185]]
0.863
